### ISSUE TITLE
Feature Request: Add setting to offset calibrate the temperature

### ISSUE THREAD

**Issue by nickbroon** [marcelbuesing/bme680#11]
The python library provides this (https://github.com/pimoroni/bme680-python/pull/13) based on details gleamed from the Bosch drivers (https://github.com/pimoroni/bme680-python/issues/11) which also allows to set a temperature offset as the device is not factory calibrated.

**Comment by nickbroon** [comment]
I thought about adding a t_fine member to the CalibData struct, and modifying that with an offset (basically just doing the same as python code does in the previous mentioned links), but I've noticed in the commit below, that such a member previously existed but was removed and instead t_fine was explicitly passed to temp/pressure/humidity function instead. Was there reason for removing t_fine from the CalibData struct? Would be acceptable to add it back, and then modify it with new adding temp_offset setting?

https://github.com/marcelbuesing/bme680/commit/6b6e19b9752c9f95350c8fdcc191771ccd41d1fd#diff-b4aea3e418ccdb71239b96952d9cddb6L229

**Comment by marcelbuesing** [comment]
Hi nick, sorry for the slow the response. I'll try to check this in the next days, thanks for digging in the commits. It does sound like a good suggestion though.

**Comment by marcelbuesing** [comment]
Ok I just added it to the `SettingsBuilder` as `with_temperature_offset(i32)`. After looking at the code again the reason why I initially moved out t_fine was that I felt that the this enforces the order of function execution.

> Temperature measurement can be enabled or skipped. Skipping the measurement is 
typically not recommended since temperature information is used to compensate temperature influences in the other parameters. [Datasheet](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BME680-DS001.pdf)

When looking at the calculation of the pressure and humidity it actually looks to me more like the temperature measurement must not be skipped.

E.g. in the C library the order of execution affect the results of
[L887](https://github.com/BoschSensortec/BME680_driver/blob/master/bme680.c#L887)/[L903](https://github.com/BoschSensortec/BME680_driver/blob/63bb5336db4659519860832be2738c685133aa33/bme680.c#L903)

What do you think about this and would you mind giving the code a try ? It's located in the offset branch.

**Comment by nickbroon** [comment]
I've had a look over https://github.com/marcelbuesing/bme680/compare/offset and this should work fine. I agree that it appears that order appears to be import in both the C and Python implementations with t_fine being an output from temperature calculation and an input for pressure/humidity. Storing it in calibration data can make appear as if pressure/humidity can be calculated independently from temperature, but your approach makes them explicitly dependant which I think is better.

**Comment by marcelbuesing** [comment]
Thank for looking at this! I've just released `0.4.0` containing the change.

**Comment by marcelbuesing** [comment]
Would you mind looking at the fix again? Sorry for this. It actually also fixes the else instead of else if case (offset > 0) that was corrected later in the python merge request.

**Comment by marcelbuesing** [comment]
Well I had to get creative, since there does not seem to be a `copysign` fn for `i32`, but I think this should do the job.
